# -*- coding: utf-8 -*-
"""euler_method.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v20cTx0NH4Ix5pK0dX8PvQwLQKJL0Dg6
"""

def euler_method(f, x0, y0, h, x_end):

    x, y = x0, y0
    while x < x_end:
      y += h * f(x,y)
      x += h
    return y

def f(x, y):
    return x + y

x0 = 0
y0 = 0
h = 0.1
x_end = 0.5

resultado = euler_method(f, x0, y0, h, x_end)

print(f"Valor aproximado de y: {resultado}")