# -*- coding: utf-8 -*-
"""newton.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v20cTx0NH4Ix5pK0dX8PvQwLQKJL0Dg6
"""

def divided_differences(x, y):

  #  Parâmetros:
  #  x - vetor de abcissas
  #  y - vetor de ordenadas

    n = len(x)
    tabela = [[0] * n for _ in range(n)]

    # Preenche a primeira coluna com os valores de y
    for i in range(n):
        tabela[i][0] = y[i]

    # Calcula as diferenças divididas
    for j in range(1, n):
        for i in range(n - j):
            tabela[i][j] = (tabela[i + 1][j - 1] - tabela[i][j - 1]) / (x[i + j] - x[i])

    return tabela

def newton_polynomial(x, y, xi):


  #  Parâmetros:
  #  x  - vetor de abcissas
  #  y  - vetor de ordenadas
  #  xi - valor a ser interpolado


    tabela = divided_differences(x, y)
    n = len(x)

    # Pega os coeficientes da tabela de diferenças divididas
    coeficientes = [tabela[0][i] for i in range(n)]

    # Usa o método de Horner para avaliar o polinômio
    yi = coeficientes[-1]
    for i in range(n - 2, -1, -1):
        yi = yi * (xi - x[i]) + coeficientes[i]

    return yi

n = 8
x = [500, 1000, 1500, 2000, 2500, 3000, 3500, 4000]
y = [2.74, 5.48, 7.90, 11.00, 13.93, 16.43, 20.24, 23.52]
xi = 3200

yi = newton_polynomial(x, y, xi)
print(f"O valor interpolado em x = {xi} é y = {yi}")