# -*- coding: utf-8 -*-
"""simpson_1_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v20cTx0NH4Ix5pK0dX8PvQwLQKJL0Dg6
"""

def f(x):
    return x*cos(x)

def simpsons_rule(a, b, n):

    if n % 2 != 0:
        raise ValueError("O número de subintervalos deve ser par para o método de 1/3 de Simpson.")

    h = (b - a) / n
    integral = f(a) + f(b)

    for i in range(1, n):
        x = a + i * h
        if i % 2 == 0:
            integral += 2 * f(x)
        else:
            integral += 4 * f(x)

    integral *= h / 3
    return integral