# -*- coding: utf-8 -*-
"""simpson_3_8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v20cTx0NH4Ix5pK0dX8PvQwLQKJL0Dg6
"""

def f(x):
    return e**x

def simpsons_38_rule(a, b, n):

    if n % 3 != 0:
        raise ValueError("O número de subintervalos deve ser múltiplo de 3 para o método 3/8 de Simpson.")

    h = (b - a) / n
    integral = f(a) + f(b)

    for i in range(1, n):
        x = a + i * h
        if i % 3 == 0:
            integral += 2 * f(x)
        else:
            integral += 3 * f(x)

    integral *= 3 * h / 8
    return integral