# -*- coding: utf-8 -*-
"""trapezoidal_rule.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v20cTx0NH4Ix5pK0dX8PvQwLQKJL0Dg6
"""

def f(x):
  return 5*cos(0.5)

def trapezoidal_rule(a,b,n):
  h = (b-a) / n
  result = 0.5 * (f(a) + f(b))

  for i in range(1,n):
    x = a + i * h
    result += f(x)

  result *= h
  return result