# -*- coding: utf-8 -*-
"""lagrange.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v20cTx0NH4Ix5pK0dX8PvQwLQKJL0Dg6
"""

def lagrange_interpolation(n, x, y, xi):

    # Parâmetros:
    # n  - número de pontos
    # x  - vetor de abcissas
    # y  - vetor de ordenadas
    # xi - valor a ser interpolado

    yi = 0
    for i in range(n):
        # Calcula o termo L_i(xi)
        L = 1
        for j in range(n):
            if i != j:
                L *= (xi - x[j]) / (x[i] - x[j])
        # Soma o termo multiplicado por y_i
        yi += L * y[i]
    return yi

n = 8
x = [500, 1000, 1500, 2000, 2500, 3000, 3500, 4000]
y = [2.74, 5.48, 7.90, 11.00, 13.93, 16.43, 20.24, 23.52]
xi = 3200

yi = lagrange_interpolation(n, x, y, xi)
print(f"O valor interpolado em x = {xi} é y = {yi}")