# -*- coding: utf-8 -*-
"""cholesky.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v20cTx0NH4Ix5pK0dX8PvQwLQKJL0Dg6
"""

def matrix_decomposition(A):
  n = A.shape[0]
  L = np.zeros_like(A)

  for i in range(n):
    for j in range(i+1):
      sum_k = sum(L[i][k] * L[j][k] for k in range (j))

      if i == j:
        L[i][j] = np.sqrt(A[i][i] - sum_k)
      else:
        L[i][j] = (A[i][j] - sum_k) / L[j][j]

  print("Matriz decomposta: \n",L)
  return L

def solve_cholensky(L, b):

  y = np.zeros_like(b)
  y.dtype = 'float'
  for i in range(len(b)):
    y[i] = (b[i] - np.dot(L[i, :i], y[:i])) / L[i][i]

  x = np.zeros_like(b)
  x.dtype = 'float'
  for i in range(len(b) - 1, -1, -1):
    x[i] = (y[i] - np.dot(L.T[i, i + 1:], x[i+1:])) / L[i,i]

  return x



A = np.array([[1, 2, 1],
              [2, 6, 0],
              [1, 0, 4]], dtype=float)
b = np.array([4, 8, 5], dtype=float)


L = matrix_decomposition(A)
Result = solve_cholensky(L, b)
print("Resultado = ",Result)