# -*- coding: utf-8 -*-
"""cholesky_pivot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v20cTx0NH4Ix5pK0dX8PvQwLQKJL0Dg6
"""

def cholesky_decomposition_with_pivoting(A):
    n = A.shape[0]
    L = np.zeros_like(A, dtype=float)
    P = np.eye(n)

    for i in range(n):
        max_index = i + np.argmax(np.abs(A[i:, i]))
        if i != max_index:

            A[[i, max_index]] = A[[max_index, i]]

            L[[i, max_index], :i+1] = L[[max_index, i], :i+1]

            P[[i, max_index]] = P[[max_index, i]]

        for j in range(i+1):
            sum_term = sum(L[i][k] * L[j][k] for k in range(j))
            if i == j:
                L[i][j] = np.sqrt(A[i][i] - sum_term)
            else:
                L[i][j] = (A[i][j] - sum_term) / L[j][j]

    return L, P

def solve_cholesky_with_pivoting(L, P, b):
    n = len(b)
    Pb = np.dot(P, b)
    y = np.zeros(n, dtype=float)
    x = np.zeros(n, dtype=float)

    for i in range(n):
        y[i] = (Pb[i] - np.dot(L[i, :i], y[:i])) / L[i, i]

    for i in range(n-1, -1, -1):
        x[i] = (y[i] - np.dot(L[i, i+1:], x[i+1:])) / L[i, i]

    return x


A = np.array([[1, 2, 1],
              [2, 6, 0],
              [1, 0, 4]], dtype=float)
b = np.array([4, 8, 5], dtype=float)

L, P = cholesky_decomposition_with_pivoting(A)
print("Matriz L:")
print(L)

Result = solve_cholesky_with_pivoting(L, P, b)
print("Resultado:")
print(Result)