# -*- coding: utf-8 -*-
"""gauss_elimination_pivot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v20cTx0NH4Ix5pK0dX8PvQwLQKJL0Dg6
"""

def gauss(A, b):

  n = len(b)
  M = np.hstack((A, b.reshape(-1,1)))

  for i in range(n):

    max_row = i + np.argmax(np.abs(M[i:,i]))
    if M[max_row, i] == 0:
      raise ValueError("Matriz é singular")


    M[[i, max_row]] = M[[max_row, i]]


    for j in range(i+1, n):
      factor = M[j,i] / M[i,i]
      M[j, i:] -= factor * M[i, i:]



  A_reduced = M[:, :-1]
  b_reduced = M[:, -1]

  x = np.linalg.solve(A_reduced, b_reduced)

  return x

A = np.array([[1, 1, 3],
              [1, 1, 4],
              [5, 2, 1]], dtype=float)
b = np.array([-2, -3, 4], dtype=float)
x = gauss(A,b)
print(x)