# -*- coding: utf-8 -*-
"""gauss_elimination.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v20cTx0NH4Ix5pK0dX8PvQwLQKJL0Dg6
"""

def gauss_elimination(A, b):

    n = len(b)
    A = A.astype(float)
    b = b.astype(float)


    for k in range(n):
        for i in range(k+1, n):
            factor = A[i, k] / A[k, k]
            A[i, k:] = A[i, k:] - factor * A[k, k:]
            b[i] = b[i] - factor * b[k]


    x = np.zeros(n)
    for i in range(n-1, -1, -1):
        x[i] = (b[i] - np.dot(A[i, i+1:], x[i+1:])) / A[i, i]

    return x

A = np.array([[1, 1, 3],
              [1, 1, 4],
              [5, 2, 1]], dtype=float)
b = np.array([-2, -3, 4], dtype=float)

solucao = gauss_elimination(A, b)
print("Solução:", solucao)