# -*- coding: utf-8 -*-
"""jacobi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v20cTx0NH4Ix5pK0dX8PvQwLQKJL0Dg6
"""

def jacobi(A, b, x0, tol=1e-10, max_iterations=100):

    n = len(A)
    x = x0.copy()

    for k in range(max_iterations):
        x_new = np.zeros_like(x)

        for i in range(n):
            s = sum(A[i][j] * x[j] for j in range(n) if j != i)
            x_new[i] = (b[i] - s) / A[i][i]


        if np.linalg.norm(x_new - x, ord=np.inf) < tol:
            return x_new

        x = x_new

    raise Exception("O método de Jacobi não convergiu dentro do número máximo de iterações")


A = np.array([[17, -2, -3],
              [-5, 21, -2],
              [-5, -5, 22]], dtype=float)

b = np.array([500, 200, 30], dtype=float)
x0 = np.zeros_like(b)

solucao = jacobi(A, b, x0)
print("Solução:", solucao)