# -*- coding: utf-8 -*-
"""lu_decomposition.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v20cTx0NH4Ix5pK0dX8PvQwLQKJL0Dg6
"""

def lu_decomposition_without_pivoting(A):
    n = A.shape[0]
    L = np.eye(n)
    U = A.copy()

    for i in range(n):
        for j in range(i+1, n):
            L[j, i] = U[j, i] / U[i, i]
            U[j, i:] -= L[j, i] * U[i, i:]

    return L, U

def solve_lu_without_pivoting(L, U, b):

    n = len(b)
    y = np.zeros(n)
    for i in range(n):
        y[i] = (b[i] - np.dot(L[i, :i], y[:i])) / L[i, i]


    x = np.zeros(n)
    for i in range(n-1, -1, -1):
        x[i] = (y[i] - np.dot(U[i, i+1:], x[i+1:])) / U[i, i]

    return x


A = np.array([[1, 2, 1],
              [2, 6, 0],
              [1, 0, 4]], dtype=float)
b = np.array([4, 8, 5], dtype=float)

L, U = lu_decomposition_without_pivoting(A)
x = solve_lu_without_pivoting(L, U, b)

print("Matriz L:")
print(L)
print("Matriz U:")
print(U)
print("Solução x:")
print(x)