# -*- coding: utf-8 -*-
"""lu_decomposition_pivot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v20cTx0NH4Ix5pK0dX8PvQwLQKJL0Dg6
"""

def lu_decomposition_with_pivoting(A):
    n = A.shape[0]
    L = np.zeros_like(A)
    U = A.copy()
    P = np.eye(n)

    for i in range(n):
        max_index = np.argmax(abs(U[i:, i])) + i

        if i != max_index:
            U[[i, max_index]] = U[[max_index, i]]

            P[[i, max_index]] = P[[max_index, i]]
            if i > 0:

                L[[i, max_index], :i] = L[[max_index, i], :i]

        for j in range(i+1, n):
            L[j, i] = U[j, i] / U[i, i]
            U[j] = U[j] - L[j, i] * U[i]

    np.fill_diagonal(L, 1)

    return P, L, U

def solve_lu(L, U, P, b):

    Pb = np.dot(P, b)


    y = np.zeros_like(b)
    for i in range(len(b)):
        y[i] = (Pb[i] - np.dot(L[i, :i], y[:i])) / L[i, i]


    x = np.zeros_like(b)
    for i in range(len(b) - 1, -1, -1):
        x[i] = (y[i] - np.dot(U[i, i+1:], x[i+1:])) / U[i, i]

    return x


A = np.array([[1, 2, 1],
              [2, 6, 0],
              [1, 0, 4]], dtype=float)
b = np.array([4, 8, 5], dtype=float)

P, L, U = lu_decomposition_with_pivoting(A)
x = solve_lu(L, U, P, b)

print("Matriz P:")
print(P)
print("Matriz L:")
print(L)
print("Matriz U:")
print(U)
print("Solução x:")
print(x)